### ISSUE TITLE
make each pipeline run name unique

### ISSUE THREAD

**Issue by codificat** [thoth-station/meteor-operator#97]
The `PipelineRun`s triggered by the CNBi controller are named after their corresponding `cnbi` object name and buildType.

Two `PipelineRun`s from the same object would have a name clash.

Each `PipelineRun` should have a unique name to prevent such a clash.

## Acceptance criteria

- [ ] each pipeline run created from the meteor operator has a unique name (possibly based on the build type, but with extra unique ids)

**Comment by VannTen** [comment]
I think we just need to use `generateName` instead of `name` in the metadata for that

**Comment by goern** [comment]
This also influences how we reconcile a PipelineRun:

1. if a PipelineRun finishes, we keep it, and if the CNBI resource gets updated, we delete the PipelineRun and create a new one (having the same name as the one before)
2. if a PR finishes, we keep it, and if the CNBI resource gets updates, we create a new PR for the new generation of the CNBI resource

2. would require use to track a generation-PR map?

**Comment by VannTen** [comment]
other possibilities:
3. Use generateName instead of name for the pipelineRun, let the apiServer handle the name uniqueness + add an annotation holding the value of the CNBi observedGeneration.
4. Intermediate CNBiVersion object (think Deployment -> ReplicaSet) and unique PipelineRun per CNBiVersion.
